document.writeln("<!-- footer -->");
document.writeln("<meta http-equiv=\'content-type\' content=\'text/html; charset=UTF-8\'>");
document.writeln("<footer class=\'container-fluid footer_bg\' id=\'footer\'>");
document.writeln("<div class=\'container\'>");
document.writeln("				<div class=\'pt30\'>");
document.writeln("					<div class=\'pull-left footer_bg_text\'>");
document.writeln("						<h2>广州维客网络有限公司</h2>");
document.writeln("						<ul>");
document.writeln("							<li>联系地址：广州市越秀区先烈中路中桥大厦</li>");
document.writeln("							<li>联系人：李先生</li>");
document.writeln("							<li>联系电话邮箱：020-36956564</li>");
document.writeln("							<li>邮箱：w1235262623@qq.com</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'pull-right text-center footer_bg_img\'>");
document.writeln("						<img src=\'images/wx.jpg\' class=\'center-block\' alt=\'\'>");
document.writeln("						<p class=\'wx_p\'>扫一扫，关注我们</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'clearfix\'></div>");
document.writeln("				<div class=\'container text-center footer_bg_p\'>");
document.writeln("					<p>版权所有     copyright ©2018 广州市维客网络技术有限公司   粤ICP备18092461号   技术支持：企泰科技</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("</footer>");
document.writeln("<!-- footer -->");