document.writeln("<div class=\'pull-right logo_top\'>");
document.writeln("			            <img src=\'images/logo.png\' alt=\'\'>");
document.writeln("			        </div>");
document.writeln("			        <div class=\'nav-table\'>");
document.writeln("			            <div class=\'nav-item\'>");
document.writeln("			                <ul class=\'list\'>");
document.writeln("			                    <li data-url=\'images/menu_bg_01.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'index.html\'>");
document.writeln("			                            <span>网站首页</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_01.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'brand.html\'>");
document.writeln("			                            <span>品牌官网</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_01.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'applets.html\'>");
document.writeln("			                            <span>小程序/微信开发</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_01.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'applets.html\'>");
document.writeln("			                            <span>App开发/系统开发</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_01.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'brand_design.html\'>");
document.writeln("			                            <span>品牌设计</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_02.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'cases.html\'>");
document.writeln("			                            <span>案例酷</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_03.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'about.html\'>");
document.writeln("			                            <span>关于weike</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_06.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'contact.html\'>");
document.writeln("			                            <span>联系我们</span></a>");
document.writeln("			                    </li>");
document.writeln("			                    <li data-url=\'images/menu_bg_05.jpg\'>");
document.writeln("			                        <a rel=\'nofollow\' href=\'news.html\'>");
document.writeln("			                            <span>最新动态</span></a>");
document.writeln("			                    </li>");
document.writeln("			                </ul>");
document.writeln("			            </div>");
document.writeln("			        </div>");