document.writeln("<!-- 在线客服 1 -->");
document.writeln("	    <!-- <div id=\'service\'>");
document.writeln("	        <ul>");
document.writeln("	            <li>");
document.writeln("	                <a href=\'javascript:void(0)\' class=\'weixin_area\'>");
document.writeln("	                    <img src=\'kefu/l02.png\' width=\'47\' height=\'49\' class=\'shows\' />");
document.writeln("	                    <img src=\'kefu/a.png\' width=\'57\' height=\'49\' class=\'hides\' />");
document.writeln("	                    <img src=\'kefu/kefu_weixin.png\' width=\'145\' class=\'weixin\' style=\'display:none;margin:-100px 57px 0 0\' />");
document.writeln("	                </a>");
document.writeln("	            </li>");
document.writeln("	            <li>");
document.writeln("	                <a href=\'http://wpa.qq.com/msgrd?v=3&uin=800022936&site=qq&menu=yes\' target=\'_blank\'>");
document.writeln("	                    <div class=\'hides\' style=\'width:161px;display:none;\' id=\'qq\'>");
document.writeln("	                        <div class=\'hides\' id=\'p1\'>");
document.writeln("	                            <img src=\'kefu/ll04.png\'>");
document.writeln("	                        </div>");
document.writeln("	                        <div class=\'hides\' id=\'p2\'><span style=\'color:#FFF;font-size:13px\'>800022936</span>");
document.writeln("	                        </div>");
document.writeln("	                    </div>");
document.writeln("	                    <img src=\'kefu/l04.png\' width=\'47\' height=\'49\' class=\'shows\' />");
document.writeln("	                </a>");
document.writeln("	            </li>");
document.writeln("	            <li id=\'tel\'>");
document.writeln("	                <a href=\'javascript:void(0)\'>");
document.writeln("	                    <div class=\'hides\' style=\'width:161px;display:none;\' id=\'tels\'>");
document.writeln("	                        <div class=\'hides\' id=\'p1\'>");
document.writeln("	                            <img src=\'kefu/ll05.png\'>");
document.writeln("	                        </div>");
document.writeln("	                        <div class=\'hides\' id=\'p3\'><span style=\'color:#FFF;font-size:12px\'>0551-65371998</span>");
document.writeln("	                        </div>");
document.writeln("	                    </div>");
document.writeln("	                    <img src=\'kefu/l05.png\' width=\'47\' height=\'49\' class=\'shows\' />");
document.writeln("	                </a>");
document.writeln("	            </li>");
document.writeln("	            <li id=\'btn\'>");
document.writeln("	                <a id=\'top_btn\'>");
document.writeln("	                    <div class=\'hides\' style=\'width:161px;display:none\'>");
document.writeln("	                        <img src=\'kefu/ll06.png\' width=\'161\' height=\'49\' />");
document.writeln("	                    </div>");
document.writeln("	                    <img src=\'kefu/l06.png\' width=\'47\' height=\'49\' class=\'shows\' />");
document.writeln("	                </a>");
document.writeln("	            </li>");
document.writeln("	        </ul>");
document.writeln("	    </div>");
document.writeln("	    <link rel=\'stylesheet\' href=\'kefu/kefu.css\'>");
document.writeln("		<script src=\'kefu/kefu.js\' type=\'text/javascript\' charset=\'utf-8\'></script> -->");
document.writeln("		<!-- 在线客服1 -->");
document.writeln("");
document.writeln("		<!-- 在线客服2 -->");
document.writeln("	    <div class=\'customer\'>");
document.writeln("			<div class=\'customer_hide\' title=\'打开客服\'></div>");
document.writeln("		    <div class=\'customer_show hide_none\'  title=\'在线客服\'>");
document.writeln("		        <div class=\'customer_title\'><a title=\'关闭\' class=\'customer_close\' href=\'javascript:void(0)\'><img src=\'kefu/kefu/online_close.gif\'/></a></div>");
document.writeln("		        <div class=\'customer_main\'>");
document.writeln("		            <div class=\'cus_group\'>");
document.writeln("		                <h3>售前客服</h3>");
document.writeln("		                <ul>");
document.writeln("		                    <li><a target=\'_blank\' href=\'http://wpa.qq.com/msgrd?v=3&uin=1476615031&site=qq&menu=yes\'><img border=\'0\' src=\'http://wpa.qq.com/pa?p=2:1476615031:51\' alt=\'点击这里给我发消息\' title=\'点击这里给我发消息\'/></a></li>");
document.writeln("		                </ul>");
document.writeln("		            </div>");
document.writeln("		            <div class=\'cus_group\'>");
document.writeln("		                <h3>售后客服</h3>");
document.writeln("		                <ul>");
document.writeln("		                    <li><a target=\'_blank\' href=\'http://wpa.qq.com/msgrd?v=3&uin=1993150735&site=qq&menu=yes\'><img border=\'0\' src=\'http://wpa.qq.com/pa?p=2:1993150735:41\' alt=\'点击这里给我发消息\' title=\'点击这里给我发消息\'/></a></li>");
document.writeln("		                </ul>");
document.writeln("		            </div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		</div>");
document.writeln("		<link rel=\'stylesheet\' href=\'kefu/kefu.css\'>");
document.writeln("		<script src=\'kefu/jquery.placeholder.min.js\' type=\'text/javascript\' charset=\'utf-8\'></script> ");
document.writeln("		<script src=\'kefu/kefu.js\' type=\'text/javascript\' charset=\'utf-8\'></script>");
document.writeln("		<!-- 在线客服2 -->");
document.writeln("	</div>");